version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
      - run: chmod +x ~/miniconda.sh && ~/miniconda.sh -b
      - run: echo 'export PATH="$HOME/miniconda3/bin:$PATH"' >> $BASH_ENV
      - run: conda create -n testenv python=3.6 pandas scikit-learn joblib Cython mkl -yq
      - run: source activate testenv
      - run: conda install pot nilearn -c conda-forge
      - run: pip install .
      - run: set-o pipefail && pytest 2>&1 | tee log.txt
