version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run: pip install --user pandas scikit-learn nilearn joblib Cython POT 
      - run: pip install --user .
      - run: set-o pipefail && pytest 2>&1 | tee log.txt
